language: php

php:
    - 5.6

env:
    - INSTALL_PHP_INVOKER=0
    - INSTALL_PHP_INVOKER=1

before_script:
    - composer install
    - sh -c "if [ '$INSTALL_PHP_INVOKER' = '1' ]; then composer require --dev --prefer-source phpunit/php-invoker:\>=1.1.0,\<1.2.0; else composer install --dev --prefer-source; fi"

script: phpunit --exclude-group FITS --bootstrap vendor/autoload.php tests

matrix:
  allow_failures:
    - php: hhvm

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#phpunit"
    use_notice: true
